package com.yq.entity.jurisdiction.role;

public class JdbMerchantUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_merchant_user.portrait
     *
     * @mbggenerated
     */
    private String portrait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.user_id
     *
     * @return the value of jdb_merchant_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.user_id
     *
     * @param userId the value for jdb_merchant_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.user_name
     *
     * @return the value of jdb_merchant_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.user_name
     *
     * @param userName the value for jdb_merchant_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.login_name
     *
     * @return the value of jdb_merchant_user.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.login_name
     *
     * @param loginName the value for jdb_merchant_user.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.password
     *
     * @return the value of jdb_merchant_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.password
     *
     * @param password the value for jdb_merchant_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.user_phone
     *
     * @return the value of jdb_merchant_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.user_phone
     *
     * @param userPhone the value for jdb_merchant_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.identity_card
     *
     * @return the value of jdb_merchant_user.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.identity_card
     *
     * @param identityCard the value for jdb_merchant_user.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_merchant_user.portrait
     *
     * @return the value of jdb_merchant_user.portrait
     *
     * @mbggenerated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_merchant_user.portrait
     *
     * @param portrait the value for jdb_merchant_user.portrait
     *
     * @mbggenerated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }
}