package com.yq.entity.jurisdiction.role;

public class JdbMenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu_role.menu_role_id
     *
     * @mbggenerated
     */
    private String menuRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu_role.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu_role.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu_role.menu_role_id
     *
     * @return the value of jdb_menu_role.menu_role_id
     *
     * @mbggenerated
     */
    public String getMenuRoleId() {
        return menuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu_role.menu_role_id
     *
     * @param menuRoleId the value for jdb_menu_role.menu_role_id
     *
     * @mbggenerated
     */
    public void setMenuRoleId(String menuRoleId) {
        this.menuRoleId = menuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu_role.menu_id
     *
     * @return the value of jdb_menu_role.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu_role.menu_id
     *
     * @param menuId the value for jdb_menu_role.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu_role.role_id
     *
     * @return the value of jdb_menu_role.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu_role.role_id
     *
     * @param roleId the value for jdb_menu_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}