package com.yq.entity.jurisdiction.menu;

public class JdbMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_img
     *
     * @mbggenerated
     */
    private String goodsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_price
     *
     * @mbggenerated
     */
    private Float goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_address
     *
     * @mbggenerated
     */
    private String goodsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.add_time
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdb_menu.goods_detail
     *
     * @mbggenerated
     */
    private String goodsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_id
     *
     * @return the value of jdb_menu.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_id
     *
     * @param goodsId the value for jdb_menu.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_name
     *
     * @return the value of jdb_menu.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_name
     *
     * @param goodsName the value for jdb_menu.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_img
     *
     * @return the value of jdb_menu.goods_img
     *
     * @mbggenerated
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_img
     *
     * @param goodsImg the value for jdb_menu.goods_img
     *
     * @mbggenerated
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_price
     *
     * @return the value of jdb_menu.goods_price
     *
     * @mbggenerated
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_price
     *
     * @param goodsPrice the value for jdb_menu.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_address
     *
     * @return the value of jdb_menu.goods_address
     *
     * @mbggenerated
     */
    public String getGoodsAddress() {
        return goodsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_address
     *
     * @param goodsAddress the value for jdb_menu.goods_address
     *
     * @mbggenerated
     */
    public void setGoodsAddress(String goodsAddress) {
        this.goodsAddress = goodsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.add_time
     *
     * @return the value of jdb_menu.add_time
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.add_time
     *
     * @param addTime the value for jdb_menu.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.status
     *
     * @return the value of jdb_menu.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.status
     *
     * @param status the value for jdb_menu.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdb_menu.goods_detail
     *
     * @return the value of jdb_menu.goods_detail
     *
     * @mbggenerated
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdb_menu.goods_detail
     *
     * @param goodsDetail the value for jdb_menu.goods_detail
     *
     * @mbggenerated
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail;
    }
}